config file changes
Updated config files:
* Reflect current code Kconfig settings.
* Changed kernel parameters now that MP init works well.

Also commented out UART devices in ACPI, to get correct IRQ:
serial8250: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A

Now the u-root uinit boot messages do show up, but the u-root banner
is missing for some reason:
Freeing unused kernel memory: 2028K
Freeing unused kernel memory: 1244K
print_req_error: I/O error, dev loop0, sector 2
EXT4-fs (loop0): unable to read superblock